# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{go_maps}
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gonow"]
  s.date = %q{2011-04-14}
  s.description = %q{Ruby API to geographic operations}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
    "Rakefile",
    "go_maps.gemspec",
    "lib/go_maps.rb",
    "lib/go_maps/address.rb",
    "lib/go_maps/address_not_found_exception.rb",
    "lib/go_maps/cep.rb",
    "lib/go_maps/direction.rb",
    "spec/data/address_error",
    "spec/data/address_success",
    "spec/data/cep_error",
    "spec/data/cep_success",
    "spec/data/direction_error",
    "spec/data/direction_success",
    "spec/data/direction_success_pt-BR",
    "spec/data/distance_error",
    "spec/data/distance_success_10.8",
    "spec/go_maps/address_spec.rb",
    "spec/go_maps/cep_spec.rb",
    "spec/go_maps/direction_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/gonow/go_maps}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Ruby API to geographic operations}
  s.test_files = [
    "spec/go_maps/address_spec.rb",
    "spec/go_maps/cep_spec.rb",
    "spec/go_maps/direction_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_runtime_dependency(%q<crack>, [">= 0.1.6"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.1"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_dependency(%q<crack>, [">= 0.1.6"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
    s.add_dependency(%q<crack>, [">= 0.1.6"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
  end
end

